language: c

compiler:
  - gcc
  - clang

install:
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - clang
    code_climate:
      repo_token: 51552819e7e08581b6feb2b76115c65d92ccb6cb8607bf61b4f726a32f671c75

script: make && make check
