#!/bin/bash

function print_return {
    if [ $1 == 0 ]; then
        echo "${green}Test passed${reset}"
    else
        echo "${red}Test failed${reset}"
    fi
}


source "scripts/test-scripts/terminal-formatting"

echo -n ${blue}${bold}

if [ -n "$1" ]; then
    export LD_PRELOAD="$PWD/$1"
    echo Preloaded library $1
else
    echo No library preloaded, testing with standard library
fi

echo ${reset}


for i in 1 2 3 4 5 7; do
    echo ${blue}Waterloo test $i ${reset}
    "tests/waterloo/test" < "scripts/test-scripts/waterloo/inputs/$i"
    echo
done

for i in 0 1 2 3 4; do
    echo "${blue}Danluu test $i ${reset}"
    "tests/danluu/test-$i"
    print_return $?
    echo
done

echo "${blue}Wisc test${reset}"
"tests/wisc/test"
print_return $?
echo

echo $reset
unset LD_PRELOAD
