#!/bin/bash

echo

if [ -n "$1" ]
then
    export LD_PRELOAD="$PWD/$1"
    echo "## Preloaded library $1 ##"
else
    echo "## Testing with standard library ##"
fi

echo

scripts/tests/waterloo/waterloo-tests
scripts/tests/danluu/danluu-tests
