CC = clang
FLAGS = -O0 -W -Wall -Wextra -g

all: test-0 test-1 test-2 test-3 test-4

test-0: test-0.c
	$(CC) $^ $(FLAGS) -o $@

test-1: test-1.c
	$(CC) $^ $(FLAGS) -o $@

test-2: test-2.c
	$(CC) $^ $(FLAGS) -o $@

test-3: test-3.c
	$(CC) $^ $(FLAGS) -o $@

test-4: test-4.c
	$(CC) $^ $(FLAGS) -o $@

clean:
	rm test-0 test-1 test-2 test-3 test-4
