#!/bin/bash

echo

GAWK_FOLDER="/home/harald/courses/edaf35/project/gawk/gawk-3.1.8"
#GAWK_FOLDER="/home/harald/courses/edaf35/project/gawk/gawk-4.1.3"

if [ ! -d $GAWK_FOLDER ]
then
    echo 'Untar gawk source and run "configure"!'
    echo
    exit 1
fi

if [ -n "$1" ]
then
    export LD_PRELOAD="$PWD/$1"
    echo "## Preloaded library $1 ##"
else
    echo "## Testing with standard library ##"
fi

echo

cd $GAWK_FOLDER
make check
