#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Usage: $0 <gawk-version> <malloc-folder>"
    exit 1
fi

reset
source "scripts/test-scripts/terminal-formatting"

GAWK_FOLDER="gawk/gawk-$1"
MALLOC_FOLDER="../../${2%/}"

echo ${blue}${bold}
echo "Linking malloc files..."

cd $GAWK_FOLDER
cp "$MALLOC_FOLDER/alloc.c" "malloc.c"
cp "$MALLOC_FOLDER/alloc.h" "alloc.h" 

echo
echo "Running make check..."
echo ${reset}
make check

echo ${reset}
