#!/bin/bash

source "scripts/test-scripts/terminal-formatting"

VERSION="3.1.8"
#VERSION="4.1.3"

if [ ! -d $GAWK_FOLDER ]; then
    echo -n ${red}${bold}
    echo 'Untar gawk source first and run "configure"'
    echo ${reset}
    exit 1
fi

echo ${blue}${bold}

if [ -n "$1" ]; then
    export LD_PRELOAD="$PWD/$1"
    echo "Preloaded library $1"
else
    echo "Testing with standard library"
fi

echo ${reset}

cd "gawk/gawk-$VERSION"
make check
