#!/bin/bash

echo

if [ -n "$1" ]
then
    export LD_PRELOAD="$PWD/$1"
    echo "## Preloaded library $1 ##"
else
    echo "## Testing with standard library ##"
fi

if [ -n "$2" ]
then
    TESTS="$2"
else
    TESTS="0 1 2 3 4"
fi

echo

for number in $TESTS
do
    TEST="tests/danluu/test-$number"
    echo "$TEST:"
    $TEST
    echo
done
